# Generated by Django 5.1.4 on 2025-01-03 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)]),
        ),
    ]
