# Generated by Django 5.1.4 on 2025-01-03 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='personal_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
